#!/usr/bin/env zsh

if [ "$#" -lt 2 ]; then
    >&2 echo "usage: $0 deploymentName resourceGroup [templateFile] [parametersFile] [composeFile]"
    exit 1
fi

deploymentName=$1
resourceGroup=$2
templateFile=${3:-Juno.AppService.Template.json}
parametersFile=${4:-Juno.AppService.Parameters.json}
composeFile=${5:-docker-compose.yml}

exec az deployment group create --name $deploymentName --resource-group $resourceGroup --template-file $templateFile --parameters @$parametersFile --parameters composeFileContent="$(cat $composeFile)" --verbose