version: '3'
services:
  wordpress:
    image: wordpress:fpm-alpine
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/wordpress:/var/www/html
  nginx:
    image: nginx:alpine
    depends_on: wordpress
    restart: always
    ports:
      - "80:80"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/wordpress:/var/www/html
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf