version: '3'
services:
  wordpress:
    image: wordpress:fpm
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/wordpress:/var/www/html
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/certs:/etc/ssl/certs
    environment:
      WORDPRESS_CONFIG_EXTRA: |
        define( 'MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL );
        define( 'MYSQL_CLIENT_CA', '/etc/ssl/certs/BaltimoreCyberTrustRoot.crt.pem' );
  nginx:
    image: nginx:latest
    depends_on: wordpress
    restart: always
    ports:
      - "80:80"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/wordpress:/var/www/html
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf