name: Build artifact

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create directory for WordPress plugins
      run: mkdir -p data/wordpress/wp-content/plugins
    - name: Download plugins
      run: wget https://downloads.wordpress.org/plugin/wp-quicklatex.latest-stable.zip
    - name: Unzip plugins
      run: unzip '*.zip' -d data/wordpress/wp-content/plugins
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: juno
        path: |
          data
          *.yml
          *.json