name: Deploy artifact

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: ./juno/Juno.AppService.Template.json
        parameters: ./juno/Juno.AppService.Parameters.json
    - name: Upload files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        protocol: ftps
        local-dir: ./juno/data/
        server-dir: site/wwwroot/
        server: ${{ secrets.FTPS_ENDPOINT }}
        username: ${{ secrets.FTPS_USERNAME }}
        password: ${{ secrets.FTPS_PASSWORD }}
