name: Deploy artifact

on:
  push:
    branches:
    - wordpress/deploy-from-github

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: ls -R
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        template: ./juno/Juno.AppService.Template.json
        parameters: ./juno/Juno.AppService.Parameters.json
